---
title: Where in the world?
subtitle: A leaflet map with the places I have flown
tags: [R,maps,leaflet]
header_img: /assets/img/blog/201905_Where-in-the-world.png
leafletmap: true
always_allow_html: yes
output: 
  md_document:
    variant: gfm
    preserve_yaml: true
---


This is a very personal post, where I just show the map of all the places I have traveled by plain



```{r setup, echo=FALSE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(global.par = TRUE)
rm(list = ls())

#output: github_document always_allow_html: yes

library(pacman)
rm(list = ls())

source("../../pass.R")

library(pacman)
p_load(dplyr,
       jsonlite,
       readxl,
       geosphere,
       leaflet,
       leaflet.extras,
       sf)


# Find airports----
myflights <- read_excel("../assets/data/flights.xlsx")
tosearch = data.frame(toloc = 
                        (sort(append(
                          myflights$start, 
                          myflights$end))),
                      stringsAsFactors = F)

tosearch = tosearch %>% 
  count(toloc) %>% 
  arrange(desc(n)) %>% 
  as.data.frame()

tosearch$tofun = gsub(" ", "+", tosearch$toloc)
tosearch$tofun = ifelse(tosearch$toloc == "San Sebastian",
                        "san+sebastian+es",
                        tosearch$tofun)

airports <- function(place, n = 1, lang = "en") {
  url = paste(
    "http://api.geonames.org/searchJSON?formatted=true&username=",
    GEONAMES_USER,
    "&style=medium&fcode=AIRP&lang=",
    lang,
    "&maxRows=",
    paste(n),
    "&q=",
    place,
    sep = ""
  )
  geonames = fromJSON(url)
  geonames = data.frame(geonames[["geonames"]])
  geonames$search = place
  geonames = geonames %>% select(tofun = search,
                                 toponymName,
                                 countryCode,
                                 long = lng,
                                 lat)
  return(geonames)
}
#Return
for (i in 1:nrow(tosearch)) {
  res = airports(tosearch[i, c("tofun")])
  row.names(res) <- i
  if (i == 1) {
    final = res
  } else {
    final = rbind(final, res)
  }
  rm(res)
}
rm(i)
final$long = as.numeric(final$long)
final$lat = as.numeric(final$lat)

#Some statistics----
#Number times per city----
ndots = left_join(tosearch, final) %>%
  select(name = toloc,
         countryCode,
         Airport = toponymName,
         n,
         long,
         lat)

# Connecting Routes----
connect = myflights %>% count(start, end) %>% arrange(desc(n))
connect = left_join(connect,
                    ndots %>%
                      select(
                        start = name,
                        long_init = long,
                        lat_init = lat
                      ))
connect = left_join(connect,
                    ndots %>%
                      select(
                        end = name,
                        long_end = long,
                        lat_end = lat
                      ))


connectflights = gcIntermediate(
  connect[, c("long_init", "lat_init")],
  connect[, c("long_end", "lat_end")],
  n = 100,
  breakAtDateLine = T,
  sp = T
  )
  
  linessf = st_as_sf(connectflights)
  data = st_sf(connect, st_geometry(linessf))
  kms = sum((as.numeric(st_length(data)) * data$n) / 1000)
  outline <- ndots[chull(ndots$long, ndots$lat), ]
  # Leaflet-----
  map <- leaflet(options = leafletOptions(minZoom = 1.25)) %>%
    addProviderTiles(providers$CartoDB.DarkMatter,
                     options = list(noWrap = TRUE,
                                    detectRetina = TRUE)) %>%
    setView(-3.56948,  40.49181, zoom = 3) %>%
    setMaxBounds(-180, -90, 180, 90) %>%
    addCircleMarkers(
      data = ndots,
      radius = ndots$n ^ (1 / 5) * 5,
      stroke = T,
      fillOpacity = 0.3,
      group = "Destinations"
    )
  map <- addPolygons(
    map = map,
    data = outline,
    lng = ~ long,
    lat = ~ lat,
    fillColor = "white",
    fillOpacity = 0.05,
    stroke = F,
    group = "Outline"
  )
  map <-
    addPolylines(
      map,
      weight = log(connect$n) * 6 + 3,
      opacity = 0.3,
      data = connectflights,
      col = "green" ,
      group = "Flights"
    )
  map <-   addEasyButton(map,
                         easyButton(
                           icon = "fa-globe",
                           title = "Zoom to Level 1",
                           onClick = JS(
                             "function(btn, map){ map.setView([ 40.49181,-3.56948],1.25); }"
                           )
                         ))
  map <- addHeatmap(
    map,
    data = ndots,
    intensity = ndots$n ^ (1 / 5),
    max = max(ndots$n ^ (1 / 5)),
    minOpacity = 0.3,
    radius = 35,
    blur = 30,
    group = "Heatmap"
  )
  
  map <-   addLayersControl(
    map,
    overlayGroups = c("Heatmap", "Destinations", "Flights", "Outline"),
    options = layersControlOptions(collapsed = TRUE)
  )
  
  map <- hideGroup(map, c("Destinations", "Flights", "Outline"))
  map
  
```




**✈️ `r format(kms, nsmall=1, big.mark=",")` kms. flown so far.**



## Top Cities

```{r Cities,echo=FALSE,  warning=FALSE, message=FALSE, tidy='styler'}
names=read.csv("https://raw.githubusercontent.com/dieghernan/Country-Codes-and-International-Organizations/master/outputs/Countrycodes.csv")
Cities =inner_join(ndots %>%
                     select(
                       City=name,
                       countryCode,
                       n
                     ), names %>% select(
                       countryCode=ISO_3166_2,
                       Country=NAME.EN,
                       Continent=CONTINENT.EN,
                       Region=SUBREGION.EN
                     ))

knitr::kable(head(Cities %>% select(
  City,
  Country,
  N=n
) %>% filter(City != "Madrid") %>% arrange(desc(N)),10),format = 'markdown')

```

## Top Countries

```{r Countries,echo=FALSE, warning=FALSE, message=FALSE, tidy='styler'}

knitr::kable(head(
  Cities  %>% filter(City != "Madrid") %>%
    select(Country,
           Continent, n) %>% group_by(Country, Continent) %>% summarise(N = sum(n)) %>%
    arrange(desc(N)),
  5),
format = 'markdown')
  
```

## Top Continents

```{r Continents, echo=FALSE, warning=FALSE, message=FALSE, tidy='styler'}

knitr::kable(head(
  Cities  %>% filter(City != "Madrid") %>%
    select(Continent, Region, n) %>% group_by(Continent, Region) %>% summarise(N = sum(n)) %>%
    arrange(desc(N)),
  5
),
format = 'markdown')
```