---
title: "We'll miss you, UK"
subtitle: "Brexit and the consequences"
tags: [R, maps, flags,sf]
last_modified_at: 2020-09-07
header_img: ./assets/img/blog/20200602_imgpost-1.png
output: 
  md_document:
    variant: gfm
    preserve_yaml: true
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "ragg_png")
knitr::opts_knit$set(global.par = TRUE)
rm(list = ls())


```


This is just a super-quick post regarding Brexit. Leaving apart economical, political and social considerations, there is another consequence, now we are one less in the EU.

We will miss you, UK, we wish you the best.

```{r 20200602_imgpost, fig.height=540/90, fig.width=810/90, message=FALSE, warning=FALSE, dev='ragg_png', results='hide', dpi=90}


library(cartography)
library(sf)
library(giscoR)


#EU
eu <- giscoR::gisco_countrycode %>% filter(eu)

# Download maps
NUTS1 <- gisco_get_nuts(epsg = 3035, country = eu$ISO3_CODE, nuts_level = 1)


UK <- gisco_get_countries(country =  "GBR", epsg = 3035)

noplot = c("FRY", "ES7", "PT2", "PT3")
NUTS1_Clean = NUTS1 %>% subset(!NUTS_ID %in% noplot) %>%
  group_by(CNTR_CODE) %>% summarise(a=dplyr::n())

# Flag image
url = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/800px-Flag_of_Europe.svg.png"

#Mask UK
flagcut = getPngLayer(NUTS1_Clean,
                       url)
# Full extent
flag = getPngLayer(NUTS1_Clean,
                       url, mask = FALSE)


par(mar = c(0, 0, 0, 0))
tilesLayer(flag, alpha = 150)
tilesLayer(flagcut, bgalpha = 0, add = T)
plot(st_geometry(UK),
     col = "white",
     border = NA,
     add = TRUE)
```

